### ISSUE TITLE
Need CI stuff

### ISSUE THREAD

**Issue by dmacthedestroyer** [infobloxopen/atlas-app-toolkit#14]
We need to run unit, integration tests and coverage reports on PRs

**Comment by ZachEddy** [comment]
I'm interested in taking this on to learn more about CI and Codecov integration (even if it's straightforward to set up). Hey @johnbelamaric, is this as simple as writing a `travis.yml` file and pushing that to master, or will someone need to log in to TravisCI via the Infobloxopen GitHub account?

**Comment by johnbelamaric** [comment]
I need to enable it in the TravisCI account. But I just did that. So now just adding a `.travis.yml` should do it.
