### ISSUE TITLE
Run the gateway and the server in the same binary?

### ISSUE THREAD

**Issue by dmacthedestroyer** [infobloxopen/atlas-app-toolkit#20]
I think doing so would make development easier because you could just `go run` a single package and be able to issue `curl` commands without having to manage two dependencies.

Thoughts?

**Comment by johnbelamaric** [comment]
Yes, I have no problem with this. You should be able to use a flag to say which one, or both, to run. Especially if this ever gets implemented: https://github.com/grpc/grpc-go/issues/906

**Comment by Evgeniy-L** [comment]
@dmacthedestroyer, I believe we can mark this as resolved?

**Comment by dmacthedestroyer** [comment]
fixed with #35
