### ISSUE TITLE
Collection operator middleware should match gRPC-gateway convention

### ISSUE THREAD

**Issue by dmacthedestroyer** [infobloxopen/atlas-app-toolkit#24]
Currently, you reference the collection operators middleware like this:
```
mw.WithCollectionOperator()
```
We should instead change `WithCollectionOperator` to match [grpc-ecosystem](https://github.com/grpc-ecosystem/go-grpc-middleware#middleware)'s naming convention:
```
collectionoperators. UnaryServerInterceptor
```
or something like that.

**Comment by Calebjh** [comment]
There are other middlewares now that break this naming convention (although less egregiously for the most part, I think, generally including "Interceptor" somewhere in the name), but this middleware has since been renamed and this issue is outdated.
