### ISSUE TITLE
Confusing size parameter to randBytes

### ISSUE THREAD

**Issue by johnsdouglass** [infobloxopen/atlas-app-toolkit#253]
https://github.com/infobloxopen/atlas-app-toolkit/blob/1705106ff7ee7137e38d23dcf3a8064d6fd4f052/bloxid/rand.go#L16

The size parameter of the randBytes function is confusing, as this function returns half the size specified. If I specify a size of 10, I would expect 10 bytes back. And if size is odd I get less than half.

**Comment by wplu** [comment]
There is probably confusion because of the use case and potential misnaming of things...

We usually want a function that returns 10 chars sprintf'ed into hex.  Since bytes in go are twice the size of chars, there is confusion.

This is usually the use case:
```
decoded = fmt.Sprintf("%x", randBytes(10))

func randBytes(size int) []byte {
	b := make([]byte, size/2)
	_, err := rand.Read(b)
	if err != nil {
		panic(err)
	}
	return b
}
```

Perhaps this is better?
```
decoded = randHexChars(10)

func randHexChars(size int) string {
    return fmt.Sprintf("%x", randBytes(size/2))
}

func randBytes(size int) []byte {
	b := make([]byte, size)
	_, err := rand.Read(b)
	if err != nil {
		panic(err)
	}
	return b
}
```

**Comment by johnsdouglass** [comment]
Yes, that's much better.

By the way, we should probably use the encoding/hex.EncodeToString function instead of fmt.Sprintf. It's a lot faster.

https://stackoverflow.com/questions/19328957/how-to-go-from-bytes-to-get-hexadecimal

**Comment by wplu** [comment]
done
