### ISSUE TITLE
Replace github.com/dgrijalva/jwt-go because of security issue

### ISSUE THREAD

**Issue by danhruby** [infobloxopen/atlas-app-toolkit#291]
`github.com/dgrijalva/jwt-go` has security issue  (https://github.com/advisories/GHSA-w73w-5m7g-f7qc) and is recommended to replace the library with `github.com/golang-jwt/jwt`

**Comment by rchowinfoblox** [comment]
Fixed in https://github.com/infobloxopen/atlas-app-toolkit/pull/318,
merged in https://github.com/infobloxopen/atlas-app-toolkit/commit/c87e65012ebb5df978dcf555e871ddd89b8aa34d
